# Generated by Django 4.0.6 on 2025-02-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('presidente', 'Presidente'), ('vice-presidente', 'Vice-Presidente'), ('secretário', 'Secretário'), ('tesoureiro', 'Tesoureiro'), ('colaborador', 'Colaborador'), ('voluntário', 'Voluntário'), ('developper', 'Developper'), ('comunicacao', 'Equipa de Comunicação'), ('eventos', 'Organização de Eventos'), ('tm_comunicacao', 'Team Manager - Comunicação'), ('tm_eventos', 'Team Manager - Eventos')], max_length=200)),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=2)),
                ('curso', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='portefolio/fotos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
