# Generated by Django 4.0.6 on 2025-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='cargo',
            field=models.CharField(choices=[('Presidente', 'presidente'), ('Vice-Presidente', 'vice-presidente'), ('Secretário', 'secretário'), ('Tesoureiro', 'tesoureiro'), ('Colaborador', 'colaborador'), ('Voluntário', 'voluntário'), ('Developper', 'developper'), ('Equipa de Comunicação', 'comunicacao'), ('Organização de Eventos', 'eventos'), ('Team Manager - Comunicação', 'tm_comunicacao'), ('Team Manager - Eventos', 'tm_eventos')], max_length=200),
        ),
    ]
