# Generated by Django 4.0.6 on 2025-02-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_alter_membro_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='portefolio/fotos/')),
            ],
        ),
    ]
