# Generated by Django 4.0.6 on 2025-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0004_alter_evento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
