# Generated by Django 4.0.6 on 2025-02-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0006_clube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='ano',
            field=models.CharField(choices=[('1º', '1º'), ('2º', '2º'), ('3º', '3º')], max_length=2),
        ),
        migrations.AlterField(
            model_name='membro',
            name='curso',
            field=models.CharField(choices=[('Licenciatura Engenharia Informática', 'LEI'), ('Licenciatura Informática de Gestão', 'LIG'), ('Licenciatura Engenhraria Informática, Redes e Telecomunicações', 'LEIRT'), ('Licenciatura Computação e Matemática Aplicada', 'LCMA'), ('Licenciatura Ciência de Dados', 'LCiD')], max_length=100),
        ),
    ]
