# Generated by Django 5.1.7 on 2025-12-29 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("link", models.URLField(blank=True, default="", null=True)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="tecweb/logos"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("backgroundColor", models.CharField(max_length=200)),
                (
                    "borderColor",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_aluno", models.CharField(max_length=9, unique=True)),
                (
                    "nome_completo",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "telemovel",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                (
                    "curso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEI", "LEI"),
                            ("LIG", "LIG"),
                            ("LEIRT", "LEIRT"),
                            ("LCD", "LCD"),
                            ("LCMA", "LCMA"),
                            ("MEISI", "MEISI"),
                            ("DI", "DI"),
                            ("Outro", "Outro"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ano_curricular",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1º Ano"), (2, "2º Ano"), (3, "3º Ano")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "certificado",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="tecweb/certificados",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tecweb.aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inquerito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consentimento",
                    models.BooleanField(
                        default=True,
                        verbose_name="Consinto que as minhas respostas sejam utilizadas, de forma anonima, para gerar insights para a melhoria das sessões futuras da Tecweb",
                    ),
                ),
                (
                    "interesse",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Interesse da temática abordada",
                    ),
                ),
                (
                    "qualidade",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Qualidade dos conteúdos apresentados",
                    ),
                ),
                (
                    "relevancia",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Relevância para o curso que frequenta",
                    ),
                ),
                (
                    "formador",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Qualidade Técnica do Formador/Orador",
                    ),
                ),
                (
                    "conteudos",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Qualidade da apresentação de conteúdos/exposição das ideias do formador/orador",
                    ),
                ),
                (
                    "satisfacao",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Classifique na seguinte escala a sua satisfação geral sobre a sessão a que assistiu.",
                    ),
                ),
                (
                    "pontos_positivos",
                    models.TextField(
                        verbose_name="Quais os pontos mais positivos da sessão a que assistiu?"
                    ),
                ),
                (
                    "sugestoes_melhoria",
                    models.TextField(
                        verbose_name="Sugestões de melhoria para a sessão a que acabou de assistir."
                    ),
                ),
                (
                    "inscricao",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquerito",
                        to="tecweb.inscricao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("linkedin", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "orcid",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                ("cv", models.TextField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="tecweb/fotos"),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "entidade",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tecweb.entidade",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SessaoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                (
                    "titulo",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "titulo_curto",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "foto_capa",
                    models.ImageField(blank=True, null=True, upload_to="tecweb/fotos"),
                ),
                (
                    "sala",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("morada", models.TextField(blank=True, default="", null=True)),
                ("objetivo", models.TextField(blank=True, default="", null=True)),
                ("prerequisitos", models.TextField(blank=True, default="")),
                ("topicos", models.TextField(blank=True, default="", null=True)),
                ("metodologia", models.TextField(blank=True, default="", null=True)),
                (
                    "resultados_esperados",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("duracao", models.TextField(blank=True, default="", null=True)),
                ("ferramentas", models.TextField(blank=True, default="", null=True)),
                (
                    "recursos_necessarios",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("vagas_totais", models.IntegerField(default=20)),
                ("inscricao_alargada", models.BooleanField()),
                (
                    "entidades",
                    models.ManyToManyField(
                        related_name="sessoes", to="tecweb.entidade"
                    ),
                ),
                (
                    "oradores",
                    models.ManyToManyField(
                        blank=True, related_name="sessoes", to="tecweb.orador"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tecweb.tipo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inscricao",
            name="sessao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tecweb.sessaoevento"
            ),
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(blank=True, default=None, null=True)),
                ("fim", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "sessao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="tecweb.sessaoevento",
                    ),
                ),
            ],
            options={
                "ordering": ["inicio"],
            },
        ),
        migrations.CreateModel(
            name="Fotografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "foto",
                    models.FileField(
                        blank=True, null=True, upload_to="tecweb/fotos/sessoes"
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotografias",
                        to="tecweb.sessaoevento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ficheiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "ficheiro",
                    models.FileField(
                        blank=True, null=True, upload_to="tecweb/ficheiros"
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficheiros",
                        to="tecweb.sessaoevento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aluno",
            name="inscricoes",
            field=models.ManyToManyField(
                related_name="alunos_inscritos",
                through="tecweb.Inscricao",
                to="tecweb.sessaoevento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscricao",
            unique_together={("aluno", "sessao")},
        ),
    ]
