services:
  web:
    build: .
    container_name: django-web
    command: gunicorn project.wsgi:application --bind 0.0.0.0:3000
    env_file:
      - .env
    volumes:
      - db_data:/data
      - media:/app/media
    ports:
      - "3000:3000"

volumes:
  db_data:
  media: