name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: deisi-apps-test-afonso-lucas-tfc/platform-ci/.github/workflows/deploy.yml@main
    with:
      targetPort: 8000
      usePersistence: true
    secrets: inherit
    